### ISSUE TITLE
Types not usable

### ISSUE THREAD

**Issue by thewilkybarkid** [alexswilliams/orcid-utils#1685]
The TypeScript definitions aren't picked up when using the library as `"types": "lib/orcid.d.ts"` is missing from `package.json` (see https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package).

With the `noImplicitAny` option enabled (part of `strict`), it results in:

```
error TS7016: Could not find a declaration file for module 'orcid-utils'. '[...]/node_modules/orcid-utils/lib/orcid.min.js' implicitly has an 'any' type.
```

With that included, however, there's still an error:

```
error TS2306: File '[...]/node_modules/orcid-utils/lib/orcid.d.ts' is not a module.
```

This is because the types file doesn't contain an export.

**Comment by alexswilliams** [comment]
Good spot, thank you!
There is a fix branch available - if you update your dependency to:
```json
  "dependencies": {
    "orcid-utils": "alexswilliams/orcid-utils#fix/1685"
  }
```
does this resolve the above issues for you?  If so, I'll  make a new release with these changes.

**Comment by thewilkybarkid** [comment]
Thanks for the quick fix, that's working for me!
